name = "reference-counter"
version = "1.0.0"
license = "BSD"
author = ["Damian Rouson, Karla Morris, and Jim Xia"]
maintainer = "damian@archaeologic.codes"
copyright = "2020-2022 Sourcery Institute"

[dependencies]
assert = {git = "https://github.com/sourceryinstitute/assert", tag = "1.3.0"}

[dev-dependencies]
veggies = {git = "https://gitlab.com/everythingfunctional/veggies", tag = "v1.0.4"}
iso_varying_string = {git = "https://gitlab.com/everythingfunctional/iso_varying_string", tag = "v3.0.2"}
